### ISSUE TITLE
Application of tests in the proposal.

### ISSUE THREAD

**Issue by felipecastrosales** [AbedElazizShe/flutter_clean_architecture#1]
I saw this structure and proposal, including the well done reading of the article and I have a doubt ⬇️ 

How would the application of tests for each `packages`/`plugins` external to `lib` really be? 
- Like for example the `data` layer, would they be inside `/test` or would there be an **_inner layer for that_**? 

What would be the proposal for this needed, are there **examples**? 

Thanks!

**Comment by felipecastrosales** [comment]
Or rather, I just saw that it's internal.

Does this take the responsibility of having a /test or should /test be in the lib now?

Sorry for not being very clear earlier.

**Comment by AbedElazizShe** [comment]
Hi @felipecastrosales, thank you for your question.

The idea is to have tests for each of the layers, the tests are focused and isolated from other layers, including lib (presentation). So yes, the test should be inside each layer by itself.

When implementing the feature, you can write widget, and state management tests, for example, if you are using a bloc, you can test the bloc by mocking the use-cases from domain - assuming you're calling the use cases from bloc.

Does this answer your question? Please let me know if I misunderstood it.

Thank you.
